
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AuthProvider } from "./(auth)/auth/authProvider";
import UserProvider from "@/components/UserProvider";
import WhatsAppWidget from "@/components/WhatsAppWidget"; // Import the WhatsApp widget

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "World Wide Admission",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <UserProvider />
          {children}
          <WhatsAppWidget /> {/* WhatsApp widget added globally */}
        </AuthProvider>
      </body>
    </html>
  );
}
