export const majorsAndDisciplines = [
  "Physics",
  "Chemistry",
  "Biology",
  "Earth & Environmental Sciences",
  "Astronomy",
  "Biotechnology",
  "Geology",
  "Oceanography",
  "Computer Science",
  "Information Technology",
  "Artificial Intelligence (AI)",
  "Cybersecurity",
  "Data Science & Analytics",
  "Software Engineering",
  "Game Development",
  "Engineering",
  "Robotics & Automation",
  "Mathematics",
  "Statistics",
  "Actuarial Science",
  "Medicine (MBBS, MD)",
  "Dentistry",
  "Nursing",
  "Pharmacy",
  "Physiotherapy",
  "Public Health",
  "Veterinary Science",
  "Biochemistry",
  "Molecular Biology",
  "Neuroscience",
  "Genetics",
  "Microbiology",
  "Immunology",
  "Radiology & Medical Imaging",
  "Nutrition & Dietetics",
  "Occupational Therapy",
  "Speech & Language Therapy",
  "Business Administration",
  "Marketing",
  "Human Resource Management",
  "Operations Management",
  "Supply Chain Management",
  "Financial Management",
  "Investment & Asset Management",
  "Banking & Risk Management",
  "Accounting & Auditing",
  "Economics",
  "Law",
  "International Law",
  "Political Science",
  "Public Administration",
  "International Relations",
  "Psychology",
  "Social Work",
  "Graphic Design",
  "Fashion Design",
  "Interior Design",
  "Architecture",
  "Theatre & Drama",
  "Film & Television",
  "Music Performance & Production",
  "Dance",
  "Journalism",
  "Public Relations (PR)",
  "Digital Media",
  "Advertising",
  "Education & Pedagogy",
  "Agricultural Sciences",
  "Food Science & Technology",
  "Tourism & Travel Management",
  "Event Management",
  "Culinary Arts",
  "Gender Studies",
  "Visual Arts",
  "Sports and Exercise Sciences",
  "Media & Communication",
];

export const studyDestinations = [
  "United States",
  "United Kingdom",
  "Canada",
  "Australia",
  "Germany",
  "Malaysia",
  "Ireland",
  "New Zealand",
  "Italy",
];
