export const majorsAndDisciplines = [
    "Physics",
    "Chemistry",
    "Biology",
    "Earth & Environmental Sciences",
    "Astronomy",
    "Biotechnology",
    "Geology",
    "Oceanography",
    "Computer Science",
    "Information Technology",
    "Artificial Intelligence (AI)",
    "Cybersecurity",
    "Data Science & Analytics",
    "Software Engineering",
    "Game Development",
    "Engineering",
    "Robotics & Automation",
    "Mathematics",
    "Statistics",
    "Actuarial Science",
    "Medicine (MBBS, MD)",
    "Dentistry",
    "Nursing",
    "Pharmacy",
    "Physiotherapy",
    "Public Health",
    "Veterinary Science",
    "Biochemistry",
    "Molecular Biology",
    "Neuroscience",
    "Genetics",
    "Microbiology",
    "Immunology",
    "Radiology & Medical Imaging",
    "Nutrition & Dietetics",
    "Occupational Therapy",
    "Speech & Language Therapy",
    "Business Administration",
    "Marketing",
    "Human Resource Management",
    "Operations Management",
    "Supply Chain Management",
    "Financial Management",
    "Investment & Asset Management",
    "Banking & Risk Management",
    "Accounting & Auditing",
    "Economics",
    "Law",
    "International Law",
    "Political Science",
    "Public Administration",
    "International Relations",
    "Psychology",
    "Social Work",
    "Graphic Design",
    "Fashion Design",
    "Interior Design",
    "Architecture",
    "Theatre & Drama",
    "Film & Television",
    "Music Performance & Production",
    "Dance",
    "Journalism",
    "Public Relations (PR)",
    "Digital Media",
    "Advertising",
    "Education & Pedagogy",
    "Agricultural Sciences",
    "Food Science & Technology",
    "Tourism & Travel Management",
    "Event Management",
    "Culinary Arts",
    "Gender Studies",
    "Visual Arts",
    "Sports and Exercise Sciences",
    "Media & Communication"
];

export const studyDestinations = [
    "Pakistan",
    "India",
    "USA",
    "UK",
    "Germany",
    "Canada",
    "Australia",
    "New Zealand",
    "Japan",
    "Singapore",
    "China",
    "South Korea",
    "Malaysia",
    "France",
    "Italy",
    "Spain",
    "Sweden",
    "Denmark",
    "Finland",
    "Norway",
    "Netherlands",
    "Switzerland",
    "Ireland",
    "Russia",
    "UAE",
    "Brazil",
    "Mexico",
    "South Africa",
    "Any Other (Specify)"
];