import { z } from "zod"

export const degreeTypes = {
    Matric: {
        subjects: ["Biology", "Computer Science", "Arts and Humanities", "Commerce"],
        gradingLabel: "Percentage",
        gradingPlaceholder: "e.g., 85%",
        gradingOptions: [
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 85%)" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
            { value: "pass_fail", label: "Pass/Fail Scale", placeholder: "Pass or Fail" },
        ],
    },
    "O Levels": {
        subjects: ["Medical Science", "Engineering", "Computer Science", "Business", "Arts & Humanities"],
        gradingLabel: "Grade",
        gradingPlaceholder: "e.g., A*, A, B",
        gradingOptions: [
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A*)" },
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 85%)" },
        ],
    },
    Intermediate: {
        subjects: [
            "FSc Pre-Medical",
            "FSc-Pre Engineering",
            "ICS (Physics)",
            "ICS (Economics)",
            "ICS (Statistics)",
            "FA (Humanities)",
            "I.COM",
        ],
        gradingLabel: "Percentage",
        gradingPlaceholder: "e.g., 80%",
        gradingOptions: [
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 80%)" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
    "A Levels": {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Mathematics",
            "Further Mathematics",
            "Computer Science",
            "Economics",
            "Psychology",
            "Sociology",
            "English Language",
            "History",
            "Global Perspectives & Research",
            "Media Studies",
            "Urdu",
            "Information Technology",
            "English Literature",
            "Business",
            "Politics",
            "Law",
            "Design and Technology",
            "Electronics",
            "Health and Social Care",
            "Accounting",
            "Art and Design",
            "Philosophy",
            "Religious Studies",
            "Classics",
            "History of Art",
            "French",
            "Spanish",
            "Classical Civilization",
            "Geography",
            "Fashion & Textiles",
            "Photography",
            "German",
            "Latin",
            "Environmental Management",
            "Marine Science",
            "Travel and Tourism",
            "Physical Education / Sports Science",
            "Music",
            "Drama / Theatre Studies",
            "Development Studies",
            "Foreign Language (Other)",
            "Any Other (Specify)",
        ],
        gradingLabel: "Grade",
        gradingPlaceholder: "e.g., A*, A, B",
        gradingOptions: [
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A*)" },
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 85%)" },
        ],
        maxSubjects: 3, // A-levels allow selecting 3 subjects
    },
    "Bachelor's (2 Years)": {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Earth & Environmental Sciences",
            "Astronomy",
            "Biotechnology",
            "Geology",
            "Oceanography",
            "Computer Science",
            "Information Technology",
            "Artificial Intelligence (AI)",
            "Cybersecurity",
            "Data Science & Analytics",
            "Software Engineering",
            "Game Development",
            "Engineering",
            "Robotics & Automation",
            "Mathematics",
            "Statistics",
            "Actuarial Science",
            "Medicine (MBBS, MD)",
            "Dentistry",
            "Nursing",
            "Pharmacy",
            "Physiotherapy",
            "Public Health",
            "Veterinary Science",
            "Biochemistry",
            "Molecular Biology",
            "Neuroscience",
            "Genetics",
            "Microbiology",
            "Immunology",
            "Radiology & Medical Imaging",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Speech & Language Therapy",
            "Business Administration",
            "Marketing",
            "Human Resource Management",
            "Operations Management",
            "Supply Chain Management",
            "Financial Management",
            "Investment & Asset Management",
            "Banking & Risk Management",
            "Accounting & Auditing",
            "Economics",
            "Law",
            "International Law",
            "Political Science",
            "Public Administration",
            "International Relations",
            "Psychology",
            "Social Work",
            "Graphic Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Theatre & Drama",
            "Film & Television",
            "Music Performance & Production",
            "Dance",
            "Journalism",
            "Public Relations (PR)",
            "Digital Media",
            "Advertising",
            "Education & Pedagogy",
            "Agricultural Sciences",
            "Food Science & Technology",
            "Tourism & Travel Management",
            "Event Management",
            "Culinary Arts",
            "Gender Studies",
            "Visual Arts",
            "Sports and Exercise Sciences",
            "Media & Communication",
            "Marine Science",
            "Forestry",
            "Horticulture and Crop Science",
            "Aviation Studies",
            "Film Studies",
            "Fine Arts",
            "Project Management",
            "Finance",
            "Commerce",
            "Taxation",
            "Animation",
            "Teaching",
            "Ecology",
            "Hospitality Management",
            "History",
            "Literature",
            "Creative Writing",
            "Clinical Psychology",
            "Botany",
            "Anatomy",
            "Zoology",
            "Archaeology",
            "Sociology",
            "Criminology",
            "Modern Languages & Linguistics",
            "Other (My exact major is not listed)",
        ],
        gradingLabel: "CGPA",
        gradingPlaceholder: "e.g., 3.5/4.0",
        gradingOptions: [
            { value: "cgpa", label: "CGPA Grade Scale", placeholder: "CGPA obtained (e.g., 3.5) / Out of (e.g., 4.0)" },
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 85%)" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
    "Bachelor's (4 Years)": {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Earth & Environmental Sciences",
            "Astronomy",
            "Biotechnology",
            "Geology",
            "Oceanography",
            "Computer Science",
            "Information Technology",
            "Artificial Intelligence (AI)",
            "Cybersecurity",
            "Data Science & Analytics",
            "Software Engineering",
            "Game Development",
            "Engineering",
            "Robotics & Automation",
            "Mathematics",
            "Statistics",
            "Actuarial Science",
            "Medicine (MBBS, MD)",
            "Dentistry",
            "Nursing",
            "Pharmacy",
            "Physiotherapy",
            "Public Health",
            "Veterinary Science",
            "Biochemistry",
            "Molecular Biology",
            "Neuroscience",
            "Genetics",
            "Microbiology",
            "Immunology",
            "Radiology & Medical Imaging",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Speech & Language Therapy",
            "Business Administration",
            "Marketing",
            "Human Resource Management",
            "Operations Management",
            "Supply Chain Management",
            "Financial Management",
            "Investment & Asset Management",
            "Banking & Risk Management",
            "Accounting & Auditing",
            "Economics",
            "Law",
            "International Law",
            "Political Science",
            "Public Administration",
            "International Relations",
            "Psychology",
            "Social Work",
            "Graphic Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Theatre & Drama",
            "Film & Television",
            "Music Performance & Production",
            "Dance",
            "Journalism",
            "Public Relations (PR)",
            "Digital Media",
            "Advertising",
            "Education & Pedagogy",
            "Agricultural Sciences",
            "Food Science & Technology",
            "Tourism & Travel Management",
            "Event Management",
            "Culinary Arts",
            "Gender Studies",
            "Visual Arts",
            "Sports and Exercise Sciences",
            "Media & Communication",
            "Marine Science",
            "Forestry",
            "Horticulture and Crop Science",
            "Aviation Studies",
            "Film Studies",
            "Fine Arts",
            "Project Management",
            "Finance",
            "Commerce",
            "Taxation",
            "Animation",
            "Teaching",
            "Ecology",
            "Hospitality Management",
            "History",
            "Literature",
            "Creative Writing",
            "Clinical Psychology",
            "Botany",
            "Anatomy",
            "Zoology",
            "Archaeology",
            "Sociology",
            "Criminology",
            "Modern Languages & Linguistics",
            "Other (My exact major is not listed)",
        ],
        gradingLabel: "CGPA",
        gradingPlaceholder: "e.g., 3.5/4.0",
        gradingOptions: [
            { value: "cgpa", label: "CGPA Grade Scale", placeholder: "CGPA obtained (e.g., 3.5) / Out of (e.g., 4.0)" },
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 85%)" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
    "Master's": {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Earth & Environmental Sciences",
            "Astronomy",
            "Biotechnology",
            "Geology",
            "Oceanography",
            "Computer Science",
            "Information Technology",
            "Artificial Intelligence (AI)",
            "Cybersecurity",
            "Data Science & Analytics",
            "Software Engineering",
            "Game Development",
            "Engineering",
            "Robotics & Automation",
            "Mathematics",
            "Statistics",
            "Actuarial Science",
            "Medicine (MBBS, MD)",
            "Dentistry",
            "Nursing",
            "Pharmacy",
            "Physiotherapy",
            "Public Health",
            "Veterinary Science",
            "Biochemistry",
            "Molecular Biology",
            "Neuroscience",
            "Genetics",
            "Microbiology",
            "Immunology",
            "Radiology & Medical Imaging",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Speech & Language Therapy",
            "Business Administration",
            "Marketing",
            "Human Resource Management",
            "Operations Management",
            "Supply Chain Management",
            "Financial Management",
            "Investment & Asset Management",
            "Banking & Risk Management",
            "Accounting & Auditing",
            "Economics",
            "Law",
            "International Law",
            "Political Science",
            "Public Administration",
            "International Relations",
            "Psychology",
            "Social Work",
            "Graphic Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Theatre & Drama",
            "Film & Television",
            "Music Performance & Production",
            "Dance",
            "Journalism",
            "Public Relations (PR)",
            "Digital Media",
            "Advertising",
            "Education & Pedagogy",
            "Agricultural Sciences",
            "Food Science & Technology",
            "Tourism & Travel Management",
            "Event Management",
            "Culinary Arts",
            "Gender Studies",
            "Visual Arts",
            "Sports and Exercise Sciences",
            "Media & Communication",
            "Marine Science",
            "Forestry",
            "Horticulture and Crop Science",
            "Aviation Studies",
            "Film Studies",
            "Fine Arts",
            "Project Management",
            "Finance",
            "Commerce",
            "Taxation",
            "Animation",
            "Teaching",
            "Ecology",
            "Hospitality Management",
            "History",
            "Literature",
            "Creative Writing",
            "Clinical Psychology",
            "Botany",
            "Anatomy",
            "Zoology",
            "Archaeology",
            "Sociology",
            "Criminology",
            "Modern Languages & Linguistics",
            "Other (My exact major is not listed)",
        ],
        gradingLabel: "CGPA",
        gradingPlaceholder: "e.g., 3.7/4.0",
        gradingOptions: [
            { value: "cgpa", label: "CGPA Grade Scale", placeholder: "CGPA obtained (e.g., 3.7) / Out of (e.g., 4.0)" },
            { value: "percentage", label: "Percentage Grade Scale", placeholder: "Enter your percentage (e.g., 88%)" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
    MPhil: {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Earth & Environmental Sciences",
            "Astronomy",
            "Biotechnology",
            "Geology",
            "Oceanography",
            "Computer Science",
            "Information Technology",
            "Artificial Intelligence (AI)",
            "Cybersecurity",
            "Data Science & Analytics",
            "Software Engineering",
            "Game Development",
            "Engineering",
            "Robotics & Automation",
            "Mathematics",
            "Statistics",
            "Actuarial Science",
            "Medicine (MBBS, MD)",
            "Dentistry",
            "Nursing",
            "Pharmacy",
            "Physiotherapy",
            "Public Health",
            "Veterinary Science",
            "Biochemistry",
            "Molecular Biology",
            "Neuroscience",
            "Genetics",
            "Microbiology",
            "Immunology",
            "Radiology & Medical Imaging",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Speech & Language Therapy",
            "Business Administration",
            "Marketing",
            "Human Resource Management",
            "Operations Management",
            "Supply Chain Management",
            "Financial Management",
            "Investment & Asset Management",
            "Banking & Risk Management",
            "Accounting & Auditing",
            "Economics",
            "Law",
            "International Law",
            "Political Science",
            "Public Administration",
            "International Relations",
            "Psychology",
            "Social Work",
            "Graphic Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Theatre & Drama",
            "Film & Television",
            "Music Performance & Production",
            "Dance",
            "Journalism",
            "Public Relations (PR)",
            "Digital Media",
            "Advertising",
            "Education & Pedagogy",
            "Agricultural Sciences",
            "Food Science & Technology",
            "Tourism & Travel Management",
            "Event Management",
            "Culinary Arts",
            "Gender Studies",
            "Visual Arts",
            "Sports and Exercise Sciences",
            "Media & Communication",
            "Marine Science",
            "Forestry",
            "Horticulture and Crop Science",
            "Aviation Studies",
            "Film Studies",
            "Fine Arts",
            "Project Management",
            "Finance",
            "Commerce",
            "Taxation",
            "Animation",
            "Teaching",
            "Ecology",
            "Hospitality Management",
            "History",
            "Literature",
            "Creative Writing",
            "Clinical Psychology",
            "Botany",
            "Anatomy",
            "Zoology",
            "Archaeology",
            "Sociology",
            "Criminology",
            "Modern Languages & Linguistics",
            "Other (My exact major is not listed)",
        ],
        gradingLabel: "CGPA",
        gradingPlaceholder: "e.g., 3.8/4.0",
        gradingOptions: [
            { value: "cgpa", label: "CGPA Grade Scale", placeholder: "CGPA obtained (e.g., 3.8) / Out of (e.g., 4.0)" },
            { value: "pass_fail", label: "Pass/Fail Scale", placeholder: "Pass or Fail" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
    PhD: {
        subjects: [
            "Physics",
            "Chemistry",
            "Biology",
            "Earth & Environmental Sciences",
            "Astronomy",
            "Biotechnology",
            "Geology",
            "Oceanography",
            "Computer Science",
            "Information Technology",
            "Artificial Intelligence (AI)",
            "Cybersecurity",
            "Data Science & Analytics",
            "Software Engineering",
            "Game Development",
            "Engineering",
            "Robotics & Automation",
            "Mathematics",
            "Statistics",
            "Actuarial Science",
            "Medicine (MBBS, MD)",
            "Dentistry",
            "Nursing",
            "Pharmacy",
            "Physiotherapy",
            "Public Health",
            "Veterinary Science",
            "Biochemistry",
            "Molecular Biology",
            "Neuroscience",
            "Genetics",
            "Microbiology",
            "Immunology",
            "Radiology & Medical Imaging",
            "Nutrition & Dietetics",
            "Occupational Therapy",
            "Speech & Language Therapy",
            "Business Administration",
            "Marketing",
            "Human Resource Management",
            "Operations Management",
            "Supply Chain Management",
            "Financial Management",
            "Investment & Asset Management",
            "Banking & Risk Management",
            "Accounting & Auditing",
            "Economics",
            "Law",
            "International Law",
            "Political Science",
            "Public Administration",
            "International Relations",
            "Psychology",
            "Social Work",
            "Graphic Design",
            "Fashion Design",
            "Interior Design",
            "Architecture",
            "Theatre & Drama",
            "Film & Television",
            "Music Performance & Production",
            "Dance",
            "Journalism",
            "Public Relations (PR)",
            "Digital Media",
            "Advertising",
            "Education & Pedagogy",
            "Agricultural Sciences",
            "Food Science & Technology",
            "Tourism & Travel Management",
            "Event Management",
            "Culinary Arts",
            "Gender Studies",
            "Visual Arts",
            "Sports and Exercise Sciences",
            "Media & Communication",
            "Marine Science",
            "Forestry",
            "Horticulture and Crop Science",
            "Aviation Studies",
            "Film Studies",
            "Fine Arts",
            "Project Management",
            "Finance",
            "Commerce",
            "Taxation",
            "Animation",
            "Teaching",
            "Ecology",
            "Hospitality Management",
            "History",
            "Literature",
            "Creative Writing",
            "Clinical Psychology",
            "Botany",
            "Anatomy",
            "Zoology",
            "Archaeology",
            "Sociology",
            "Criminology",
            "Modern Languages & Linguistics",
            "Other (My exact major is not listed)",
        ],
        gradingLabel: "CGPA",
        gradingPlaceholder: "e.g., 3.8/4.0",
        gradingOptions: [
            { value: "cgpa", label: "CGPA Grade Scale", placeholder: "CGPA obtained (e.g., 3.8) / Out of (e.g., 4.0)" },
            { value: "pass_fail", label: "Pass/Fail Scale", placeholder: "Pass or Fail" },
            { value: "letter", label: "Letter Grade Scale", placeholder: "Enter your Letter Grade (e.g., A+)" },
        ],
    },
} as const

export type DegreeType = keyof typeof degreeTypes

export const educationSchema = z
    .object({
        highestDegree: z.string().min(1, "Please select a degree"),
        subjectName: z.union([
            z.string().min(1, "Please select a subject"),
            z.array(z.string())
                .min(1, "Please select at least one subject")
                .max(3, "Maximum 3 subjects allowed for A-levels"),
        ]),
        customSubjects: z.array(z.string()).optional(), // For "Any Other (Specify)" option
        streamCategory: z.string().optional(), // For categorizing custom subjects
        institutionAttended: z.string().min(1, "Institution name is required"),
        gradingType: z.string().min(1, "Please select grading type"),
        marks: z.string().min(1, "Marks/CGPA is required"),
        cgpaOutOf: z.string().optional(), // For CGPA scale (e.g., 4.0, 5.0, 10.0)
        degreeStartDate: z
            .date({
                required_error: "Start date is required",
            })
            .optional()
            .nullable(),
        degreeEndDate: z
            .date({
                required_error: "End date is required",
            })
            .optional()
            .nullable(),
    })
    .refine(
        (data) => {
            if (data.degreeStartDate && data.degreeEndDate) {
                return data.degreeEndDate > data.degreeStartDate
            }
            return true
        },
        {
            message: "End date must be after start date",
            path: ["degreeEndDate"],
        },
    )

export const formSchema = z.object({
    educationalBackground: z.array(educationSchema).min(1, "At least one educational background is required"),
})

export type FormData = z.infer<typeof formSchema>
export type EducationData = z.infer<typeof educationSchema>
