import type { Metadata } from "next";
import { AuthProvider } from "../(auth)/auth/authProvider";
import MobileNavbar from "@/components/MobileNavbar";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "World Wide Admission",
  description: "Generated by create next app",
};
export default function PagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MobileNavbar />
        <Navbar/>
        <AuthProvider>{children}</AuthProvider>
        <Footer />
      </body>
    </html>
  );
}



